/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.ufsc;

import br.ufsc.view.GUI;

public class App {


    public static void main(String[] args) {
        
        GUI.main(args);
    }
}
