/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.ufsc.view;


import com.pixelduke.transit.Style;
import com.pixelduke.transit.TransitTheme;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;


public class GUI extends Application{
    
    private String TITULOJANELA ="Abre Composicoes SINAPI";

    
    @Override
    public void start(Stage telaP) throws Exception {
        FXMLLoader loader = new FXMLLoader(getClass().getClassLoader().getResource("view/telaPrincipal.fxml"));
        Parent raiz = loader.load();
        
        //Define o titulo da janela (stage) e o icone
        telaP.setTitle(TITULOJANELA);
        telaP.getIcons().add(new Image(getClass().getClassLoader().getResourceAsStream("icons/ufsc_fundo_claro.png")));
        
        //Cria a cena
        Scene cena = new Scene(raiz);
        
        // Aplica o tema da interface
        TransitTheme tema = new TransitTheme(Style.LIGHT);
        tema.setScene(cena);
        
        //Coloca a cena criada no palco telaPrincipal
        telaP.setScene(cena);
        //Cria uma instancia do controlador de tabelas editaveis, necessario
        //para recuperar os dados inseridos pelo ususario.
        TelaPrincipalController controlador = loader.getController();
        
        telaP.show();
        
    }
    public static void main(String[] args) {
        launch(args);
    }
}
